config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :shows
  resources :seats
  resources :bookings
  resources :movies
  get 'signup_page', to: 'admins#index'
  post 'signup', to: 'admins#create'
  post 'login', to: 'sessions#create'
  get '/', to: 'sessions#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :seats

    belongs_to :show
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :shows
end

app/models/screen.rb
class Screen < ApplicationRecord
    has_many :shows
end

app/models/seat.rb
class Seat < ApplicationRecord
    belongs_to :booking, optional: true
end

app/models/show.rb
class Show < ApplicationRecord
    has_many :bookings

    belongs_to :movie
    belongs_to :screen
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    def index
        
    end

    def create
        admin = Admin.create(name: params["full_name"], email: params["email"], password_digest: params["password"])
        if admin.save
          session[:admin_id] = admin.id
          redirect_to '/movies'
        else
          flash[:register_errors] = admin.errors.full_messages
          redirect_to '/signup_page'
        end  
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
        booking_ids = params["booking_ids"]
        @bookings = Booking.all
        show_id = Booking.find_by(id: booking_ids[0].to_i).show_id
        @show = Show.find_by(id: show_id)
        movie_id = @show.movie_id
        @movie = Movie.find_by(id: movie_id)
        seat_ids = []
        booking_ids.each do |booking_id|
            seat_ids.push(Booking.find_by(id: booking_id.to_i).seat_id)
        end
        @seats = []
        @sum = 0
        seat_ids.each do |seat_id|
            @seats.push(Seat.find_by(id: seat_id))
            @sum = @sum + Seat.find_by(id: seat_id).cost
        end

    end

    def create
        new_booking = []
        show_id = params["show_id"].to_i
        seats_array = [1, 2, 3]
        seats_array.each do |seat|
            Booking.create(show_id: show_id, seat_id: seat.to_i)
            new_booking.push(Booking.last.id)
            Seat.update(seat.to_i, booking_id: Booking.last.id)
        end
        redirect_to controller: 'bookings', action: 'index', booking_ids: new_booking
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        @movies = Movie.all
    end

    def create
        movie = Movie.create(movie_name: params["movie_name"], movie_type: params["movie_type"], duration: params["duration"])
        if movie.save
          redirect_to '/movies'
        else
          flash[:register_errors] = admin.errors.full_messages
          render "movies/create"
        end  
    end

    def destroy
        p params
        movie_id = params["movie_id"]
        Movie.delete(movie_id)
        redirect_to '/movies'
    end

    def edit
      @movie_id = params["id"]
    end

    def update
      movie_id = params.keys[7].to_i
      Movie.update(movie_id, movie_name: params["movie_name"], movie_type: params["movie_type"], duration: params["duration"])
      redirect_to '/movies'
    end

    def new
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
    def index
        @show_id =  params["show_id"].to_i
        @show = Show.find_by(id: @show_id)
        @movie = Movie.find_by(id: @show.movie_id)
        @rows = 0
        @number = 0
        @seats = Seat.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def index
    end

    def create
        admin = Admin.find_by(email: params["email"])
        if admin && admin.password_digest === params[:password]
            redirect_to '/movies'
        else
            flash[:login_errors] = ['invalid credentials']
            redirect_to '/'
        end
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    def index
        @shows = Show.all
        @count = -1
        @counts = -1
        movie_ids = []
        @movies = []
        @shows.each do |show|
            movie_ids.push(show.movie_id)
        end
        movie_ids.each do |movie_id|
            @movies.push(Movie.where(id: movie_id).pluck(:movie_name, :movie_type))
        end
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <head>
    <style>
      table, td {
        border: 3px solid black;
      }
    </style>
  </head>
  <body>
    <center>
      <h1>Congratulations!! Your Booking Is Confirmed</h1>
      <table class="table">
        <tr>
          <td>Show Timings</td>
          <td><%= @show.time %></td>
        </tr>
        <tr>
          <td>Date</td>
          <td><%= @show.date %></td>
        </tr>
        <tr>
          <td>Movie</td>
          <td><%= @movie.movie_name %></td>
        </tr>
        <tr>
          <td>Seat Selected</td>
          <td>
            <%= @seats.each do |seat| %>
              <%= seat.seat_number %>,
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Total Price</td>
          <td>₹<%= @sum %></td>
        </tr>
      </table>
      </br>
      <p><a class="button" href="/shows">Book More</a></p>
      <p><a class="button" href="/">Go Back To Home</a></p>
    </center>
  </body>
</div>

app/views/movies/edit.html.erb
<div class="container">
  <body>
    <center>
        <h1>Enter Details You Want To Edit </h1>
        <%= form_with(url: "/movies/update?#{@movie_id}", method: "PUT") do %>
          <table class="table">
            <tr>
              <td><%= label_tag(:movie_name, "Movie Name*") %></td>
              <td><%= text_field_tag(:movie_name) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:movie_type, "Movie Type*") %></td>
              <td><%= text_field_tag(:movie_type) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:duration, "Duration*") %></td>
              <td><%= text_field_tag(:duration) %></td>
            </tr>
          </table>
            <br/>
            <br/>
            <%= submit_tag("Update") %>
        <% end %>
    </center>
  </body>
</div>

app/views/movies/index.html.erb
<div class="container">
  <head>
    <style>
      table, th, td {
        border: 3px solid black;
      }
    </style>
  </head>
  <body>
    <center>
      <h1>MOVIES</h1>
      <table class="table">
        <tr>
          <th class="text-center">Movie Name</th>
          <th class="text-center">Movie Type</th>
          <th class="text-center">Duration</th>
          <th class="text-center">Click To Edit</th>
        </tr>
        <% @movies.each do |movie| %>
          <tr>
            <td class="text-center">
              <%= movie.movie_name %>
            </td>
            <td class="text-center">
              <%= movie.movie_type %>
            </td>
            <td class="text-center">
              <%= movie.duration %>
            </td>
            <td class="text-center">
              <%= link_to "Edit" , edit_movie_path(movie.id)%>
            </td>
          </tr>
        <% end %>
        <tr>
      </table>
      <p><a class="button" href="/movies/new">Add More Movies</a></p>
      <p><a class="button" href="/">LOGOUT</a></p>
    </center>
  </body>
</div>

app/views/movies/new.html.erb
<div class="container">
  <body>
    <center>
        <h1>Enter Details Of New Movie Entry</h1>
        <%= form_with(url: "/movies", method: "POST") do %>
          <table class="table">
            <tr>
              <td><%= label_tag(:movie_name, "Movie Name") %></td>
              <td><%= text_field_tag(:movie_name) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:movie_type, "Movie Type") %></td>
              <td><%= text_field_tag(:movie_type) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:duration, "Duration") %></td>
              <td><%= text_field_tag(:duration) %></td>
            </tr>
          </table>
            <br/>
            <br/>
            <%= submit_tag("Create") %>
        <% end %>
    </center>
  </body>
</div>

app/views/movies/show.html.erb
<div class="container">
  <body>
    <center>
        <h1>Enter Details Of New Movie Entry</h1>
        <%= form_with(url: "/movies", method: "POST") do %>
          <table class="table">
            <tr>
              <td><%= label_tag(:movie_name, "Movie Name") %></td>
              <td><%= text_field_tag(:movie_name) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:movie_type, "Movie Type") %></td>
              <td><%= text_field_tag(:movie_type) %></td>
            </tr>
            <br/>
            <br/>
            <tr>
              <td><%= label_tag(:duration, "Duration") %></td>
              <td><%= text_field_tag(:duration) %></td>
            </tr>
          </table>
            <br/>
            <br/>
            <%= submit_tag("Create") %>
        <% end %>
    </center>
  </body>
</div>

app/views/seats/index.html.erb
<div class="container">
  <head>
    <style>
      table, td {
        border: 3px solid black;
      }
    </style>
    <script>
      var seats_array = [];
      var count = 1;
      function setColor(btn) {
          var property = document.getElementById(btn);
          if (count == 0) {
              property.style.backgroundColor = "#FFFFFF"
              count = 1;
              seats_array.push(btn)        
          }
          else {
              property.style.backgroundColor = "#7FFF00"
              count = 0;
              seats_array.delete(btn)
          }
      }
      function redirect(){
        window.location.replace("http://localhost:3000/bookings")
      }
    </script>
  </head>
  <body>
    <center>
      <h1>Show Selected</h1>
      <table class="table">
        <tr>
          <td>
            Movie Name
          </td>
          <td>
            <%= @movie.movie_name %>
          </td>
        <tr>
        <tr>
          <td>
            Show Timings
          </td>
          <td>
            <%= @show.time %>
          </td>
        <tr>
        <tr>
          <td>
            Show Date
          </td>
          <td>
            <%= @show.date %>
          </td>
        <tr>
      </table>
      <h1>Select Seats</h1>
      <h3>!!!!!!!!!!! SCREEN !!!!!!!!!!!</h3>
      <table class="table">
        <% while @rows < 10%>
          <tr>
            <td class="text-center">
              ROW <%= @rows = @rows + 1 %>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
            <td class="text-center">
              <button type="button" onClick=setColor(id) id=<%= @number = @number + 1%>><%= @number %></button>
            </td>
          </tr>
          <% end %>
      </table>
      <br>
      <p>COST OF SEATS</p>
      <p>Row 1     = ₹150</p>
      <p>Row 2 - 9 = ₹200</p>
      <p>Row 10    = ₹300</p>
      <p><%= button_to 'Confirm Booking', {:controller => "bookings", :action => "create", :show_id => @show_id, :seats_array => [1,2,3,4] } , :method=>:post  %></p>
      <br/>
      <br/>
      <p><a class="button" href="/shows">Select Another Show</a></p>
      <p><a class="button" href="/">Go Back To Home Page</a></p>
    </center>
  </body>
</div>

app/views/shows/index.html.erb
<div class="container">
  <head>
    <style>
      table, th, td {
        border: 3px solid black;
      }
    </style>
  </head>
  <body>
    <center>
      <h1>Available Shows</h1>
      <table class="table">
        <tr>
          <th class="text-center">Timing</th>
          <th class="text-center">Date</th>
          <th class="text-center">Movie</th>
          <th class="text-center">Type</th>
          <th class="text-center">Booking</th>
        </tr>
        <% @shows.each do |show| %>
          <tr>
            <td class="text-center">
              <%= show.time %>
            </td>
            <td class="text-center">
              <%= show.date %>
            </td>
            <td class="text-center">
              <%= @movies[@count = @count + 1][0].first%>
            </td>
            <td class="text-center">
              <%= @movies[@counts = @counts + 1][0].last%>
            </td>
            <td class="text-center">
              <%= link_to "Book", seats_path(show_id: show.id)%>
            </td>
          </tr>
        <% end %>
      </table>
      <p><a href="/">Go Back To Home Page</a></p>
    </center>
  </body>
</div>